name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Set ebiten 
      run: go get github.com/hajimehoshi/ebiten
      
    - name: Set image 
      run: go get golang.org/x/image/colornames@v0.0.0-20200801110659-972c09e46d76

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
