name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.14.0'
    - name: Install dependencies
      run: |
        sudo apt-get install golang gcc libgl1-mesa-dev xorg-dev
        go version
        go get github.com/hajimehoshi/ebiten
        go get golang.org/x/image/colornames@v0.0.0-20200801110659-972c09e46d76
    - name: Run build
      run: go build .
    - name: Run testing
      run: go test -v ./Game
